export const NikeData = [
  {
    id: 1,
    mainImg: "../images/NIKE/ao2.jpg",
    extraImgList: [
      "../images/NIKE/ao2.jpg",
      "../images/NIKE/ao2.jpg",
      "../images/NIKE/ao2.jpg",
    ],
    name: "Áo sơ mi nam sọc xanh",
    brandName: "NIKE",
    code: "844931-002",
    price: "299.000 VND",
    new: "New",
    discount: "20%",
    sizes: [37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 2,
    mainImg: "../images/NIKE/ao1.jpg",
    extraImgList: [
      "../images/NIKE/ao1.jpg",
      "../images/NIKE/ao1.jpg",
      "../images/NIKE/ao1.jpg",
    ],
    name: "Áo sơ mi nam sọc trắng",
    brandName: "NIKE",
    code: "835738-800",
    price: "299.000 VND",
    discount: "13%",
    sizes: [36, 36.5, 37, 38, 38.5, 39, 40],
  },
  {
    id: 3,
    mainImg: "../images/NIKE/ao3.jpg",
    extraImgList: [
      "../images/NIKE/ao3.jpg",
      "../images/NIKE/ao3.jpg",
      "../images/NIKE/ao3.jpg",
    ],
    name: "Áo sơ mi nam sẩm",
    brandName: "NIKE",
    code: "CD5434-100",
    price: "399.000 VND",
    discount: "9%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 4,
    mainImg: "../images/NIKE/ao4.jpg",
    extraImgList: [
      "../images/NIKE/ao4.jpg",
      "../images/NIKE/ao4.jpg",
      "../images/NIKE/ao4.jpg",
    ],
    name: "Áo sơ mi nam nâu sẩm",
    brandName: "NIKE",
    code: "AQ1090-002",
    price: "499.000 VND",
    discount: "11%",
    sizes: [39, 40],
  },
  {
    id: 5,
    mainImg: "../images/NIKE/ao3.jpg",
    extraImgList: [
      "../images/NIKE/ao3.jpg",
      "../images/NIKE/ao3.jpg",
      "../images/NIKE/ao3.jpg",
    ],
    name: "Áo sơ mi nam sẩm",
    brandName: "NIKE",
    code: "CD5434-100",
    price: "399.000 VND",
    discount: "9%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 6,
    mainImg: "../images/NIKE/ao4.jpg",
    extraImgList: [
      "../images/NIKE/ao4.jpg",
      "../images/NIKE/ao4.jpg",
      "../images/NIKE/ao4.jpg",
    ],
    name: "Áo sơ mi nam nâu sẩm",
    brandName: "NIKE",
    code: "AQ1090-002",
    price: "499.000 VND",
    discount: "11%",
    sizes: [39, 40],
  },
  {
    id: 7,
    mainImg: "../images/NIKE/ao1.jpg",
    extraImgList: [
      "../images/NIKE/ao1.jpg",
      "../images/NIKE/ao1.jpg",
      "../images/NIKE/ao1.jpg",
    ],
    name: "Áo sơ mi nam sọc trắng",
    brandName: "NIKE",
    code: "835738-800",
    price: "299.000 VND",
    discount: "13%",
    sizes: [36, 36.5, 37, 38, 38.5, 39, 40],
  },
  {
    id: 8,
    mainImg: "../images/NIKE/ao2.jpg",
    extraImgList: [
      "../images/NIKE/ao2.jpg",
      "../images/NIKE/ao2.jpg",
      "../images/NIKE/ao2.jpg",
    ],
    name: "Áo sơ mi nam sọc xanh",
    brandName: "NIKE",
    code: "844931-002",
    price: "299.000 VND",
    new: "New",
    discount: "20%",
    sizes: [37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 9,
    mainImg: "../images/NIKE/ao4.jpg",
    extraImgList: [
      "../images/NIKE/ao4.jpg",
      "../images/NIKE/ao4.jpg",
      "../images/NIKE/ao4.jpg",
    ],
    name: "Áo sơ mi nam nâu sẩm",
    brandName: "NIKE",
    code: "AQ1090-002",
    price: "499.000 VND",
    discount: "11%",
    sizes: [39, 40],
  },
  {
    id: 10,
    mainImg: "../images/NIKE/Nike10_1.png",
    extraImgList: [
      "../images/NIKE/Nike10_1.png",
      "../images/NIKE/Nike10_2.png",
      "../images/NIKE/Nike10_3.png",
    ],
    name: "JOYRIDE RUN CC",
    brandName: "NIKE",
    code: "AO1742-003",
    price: "1.650.000 VND",
    discount: "13%",
    sizes: [37.5, 38, 38.5, 39, 40],
  },
  {
    id: 11,
    mainImg: "../images/NIKE/Nike11_1.png",
    extraImgList: [
      "../images/NIKE/Nike11_1.png",
      "../images/NIKE/Nike11_2.png",
      "../images/NIKE/Nike11_3.png",
    ],
    name: "COURT VISION LOW HOLOGRAM",
    brandName: "NIKE",
    code: "CW5596-100",
    price: "1.900.000 VND",
    discount: "13%",
    new: "New",
    sizes: [35.5, 36, 36.5, 38, 38.5, 39, 40],
  },
  {
    id: 12,
    mainImg: "../images/NIKE/Nike12_1.png",
    extraImgList: [
      "../images/NIKE/Nike12_1.png",
      "../images/NIKE/Nike12_2.png",
      "../images/NIKE/Nike12_3.png",
    ],
    name: "DUNK HIGH UP VARSITY MAIZE",
    brandName: "NIKE",
    code: "DH3718-001",
    price: "2.490.000 VND",
    discount: "13%",
    new: "New",
    sizes: [36.5, 37, 37.5, 38, 38.5, 39],
  },
];

export const JordanData = [
  {
    id: 1,
    mainImg: "../images/JORDAN/vest1.jpg",
    extraImgList: [
      "../images/JORDAN/vest1.jpg",
      "../images/JORDAN/vest1.jpg",
      "../images/JORDAN/vest1.jpg",
    ],
    name: "Áo vest nam lịch lãm",
    brandName: "JORDAN",
    code: "553558-163",
    price: "599.000 VND",
    new: "New",
    discount: "13%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 2,
    mainImg: "../images/JORDAN/vest2.jpg",
    extraImgList: [
      "../images/JORDAN/vest2.jpg",
      "../images/JORDAN/vest2.jpg",
      "../images/JORDAN/vest2.jpg",
    ],
    name: "Áo vest nam xanh đậm",
    brandName: "JORDAN",
    code: "DH7004-102",
    price: "699.000 VND",
    discount: "15%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 3,
    mainImg: "../images/JORDAN/vest3.jpg",
    extraImgList: [
      "../images/JORDAN/vest3.jpg",
      "../images/JORDAN/vest3.jpg",
      "../images/JORDAN/vest3.jpg",
    ],
    name: "Áo vest nam phương tây",
    brandName: "JORDAN",
    code: "DH3097-001",
    price: "799.000 VND",
    discount: "18%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 4,
    mainImg: "../images/JORDAN/vest4.jpg",
    extraImgList: [
      "../images/JORDAN/vest4.jpg",
      "../images/JORDAN/vest4.jpg",
      "../images/JORDAN/vest4.jpg",
    ],
    name: "Áo vest nam đen lịch lãm",
    brandName: "JORDAN",
    code: "CZ1360-401",
    price: "899.000 VND",
    discount: "11%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 5,
    mainImg: "../images/JORDAN/vest3.jpg",
    extraImgList: [
      "../images/JORDAN/vest3.jpg",
      "../images/JORDAN/vest3.jpg",
      "../images/JORDAN/vest3.jpg",
    ],
    name: "Áo vest nam phương tây",
    brandName: "JORDAN",
    code: "DH3097-001",
    price: "799.000 VND",
    discount: "18%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 6,
    mainImg: "../images/JORDAN/vest4.jpg",
    extraImgList: [
      "../images/JORDAN/vest4.jpg",
      "../images/JORDAN/vest4.jpg",
      "../images/JORDAN/vest4.jpg",
    ],
    name: "Áo vest nam đen lịch lãm",
    brandName: "JORDAN",
    code: "CZ1360-401",
    price: "899.000 VND",
    discount: "11%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 7,
    mainImg: "../images/JORDAN/vest2.jpg",
    extraImgList: [
      "../images/JORDAN/vest2.jpg",
      "../images/JORDAN/vest2.jpg",
      "../images/JORDAN/vest2.jpg",
    ],
    name: "Áo vest nam xanh đậm",
    brandName: "JORDAN",
    code: "DH7004-102",
    price: "699.000 VND",
    discount: "15%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 8,
    mainImg: "../images/JORDAN/vest1.jpg",
    extraImgList: [
      "../images/JORDAN/vest1.jpg",
      "../images/JORDAN/vest1.jpg",
      "../images/JORDAN/vest1.jpg",
    ],
    name: "Áo vest nam lịch lãm",
    brandName: "JORDAN",
    code: "553558-163",
    price: "599.000 VND",
    new: "New",
    discount: "13%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 9,
    mainImg: "../images/JORDAN/vest1.jpg",
    extraImgList: [
      "../images/JORDAN/vest1.jpg",
      "../images/JORDAN/vest1.jpg",
      "../images/JORDAN/vest1.jpg",
    ],
    name: "Áo vest nam lịch lãm",
    brandName: "JORDAN",
    code: "553558-163",
    price: "599.000 VND",
    new: "New",
    discount: "13%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 10,
    mainImg: "../images/JORDAN/Jordan10_1.png",
    extraImgList: [
      "../images/JORDAN/Jordan10_1.png",
      "../images/JORDAN/Jordan10_2.png",
      "../images/JORDAN/Jordan10_3.png",
    ],
    name: "AIR JORDAN 5 LOW FIRE RED",
    brandName: "JORDAN",
    code: "314338-101",
    price: "1.500.000 VND",
    discount: "20%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 11,
    mainImg: "../images/JORDAN/Jordan11_1.png",
    extraImgList: [
      "../images/JORDAN/Jordan11_1.png",
      "../images/JORDAN/Jordan11_2.png",
      "../images/JORDAN/Jordan11_3.png",
    ],
    name: "AIR JORDAN 4 LIGHTNING",
    brandName: "JORDAN",
    code: "CT8527-700",
    price: "6.900.000 VND",
    discount: "20%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
  {
    id: 12,
    mainImg: "../images/JORDAN/Jordan12_1.png",
    extraImgList: [
      "../images/JORDAN/Jordan12_1.png",
      "../images/JORDAN/Jordan12_2.png",
      "../images/JORDAN/Jordan12_3.png",
    ],
    name: "AIR JORDAN 1 MID PINE GREEN MEN",
    brandName: "JORDAN",
    code: "554724-067",
    price: "4.900.000 VND",
    discount: "20%",
    sizes: [35.5, 36, 36.5, 37, 37.5, 38, 38.5, 39, 40],
  },
];

export const AdidasData = [
  {
    id: 1,
    mainImg: "../images/ADIDAS/kieu1.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu1.jpg",
      "../images/ADIDAS/kieu1.jpg",
      "../images/ADIDAS/kieu1.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "AH2203",
    price: "399.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 2,
    mainImg: "../images/ADIDAS/kieu2.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu2.jpg.jpg",
      "../images/ADIDAS/kieu2.jpg.jpg",
      "../images/ADIDAS/kieu2.jpg.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "FX8835",
    price: "599.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 3,
    mainImg: "../images/ADIDAS/kieu3.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu3.jpg",
      "../images/ADIDAS/kieu3.jpg",
      "../images/ADIDAS/kieu3.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "FW5191",
    price: "699.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 4,
    mainImg: "../images/ADIDAS/kieu4.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu4.jpg",
      "../images/ADIDAS/kieu4.jpg",
      "../images/ADIDAS/kieu4.jpg",
    ],
    name: "Áo sơ mi nam cổ tàu",
    brandName: "ADIDAS",
    code: "F99710",
    price: "299.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 5,
    mainImg: "../images/ADIDAS/kieu3.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu3.jpg",
      "../images/ADIDAS/kieu3.jpg",
      "../images/ADIDAS/kieu3.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "FW5191",
    price: "699.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 6,
    mainImg: "../images/ADIDAS/kieu2.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu2.jpg.jpg",
      "../images/ADIDAS/kieu2.jpg.jpg",
      "../images/ADIDAS/kieu2.jpg.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "FX8835",
    price: "599.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 7,
    mainImg: "../images/ADIDAS/kieu4.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu4.jpg",
      "../images/ADIDAS/kieu4.jpg",
      "../images/ADIDAS/kieu4.jpg",
    ],
    name: "Áo sơ mi nam cổ tàu",
    brandName: "ADIDAS",
    code: "F99710",
    price: "299.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 8,
    mainImg: "../images/ADIDAS/kieu1.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu1.jpg",
      "../images/ADIDAS/kieu1.jpg",
      "../images/ADIDAS/kieu1.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "AH2203",
    price: "399.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 9,
    mainImg: "../images/ADIDAS/kieu1.jpg",
    extraImgList: [
      "../images/ADIDAS/kieu1.jpg",
      "../images/ADIDAS/kieu1.jpg",
      "../images/ADIDAS/kieu1.jpg",
    ],
    name: "Áo sơ mi nam form rộng",
    brandName: "ADIDAS",
    code: "AH2203",
    price: "399.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 10,
    mainImg: "../images/ADIDAS/Adidas10_1.png",
    extraImgList: [
      "../images/ADIDAS/Adidas10_1.png",
      "../images/ADIDAS/Adidas10_2.png",
      "../images/ADIDAS/Adidas10_3.png",
    ],
    name: "NMD HU PHARRELL X BILLIONAIRE BOYS CLUB MULTI-COLOR ",
    brandName: "ADIDAS",
    code: "BB9544",
    price: "4.500.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 11,
    mainImg: "../images/ADIDAS/Adidas11_1.png",
    extraImgList: [
      "../images/ADIDAS/Adidas11_1.png",
      "../images/ADIDAS/Adidas11_2.png",
      "../images/ADIDAS/Adidas11_3.png",
    ],
    name: "ULTRA BOOST 19 WHI TE BLUE",
    brandName: "ADIDAS",
    code: "EF1340",
    price: "2.200.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 12,
    mainImg: "../images/ADIDAS/Adidas12_1.png",
    extraImgList: [
      "../images/ADIDAS/Adidas12_1.png",
      "../images/ADIDAS/Adidas12_2.png",
      "../images/ADIDAS/Adidas12_3.png",
    ],
    name: "YUNG 1 HI RES ORANGE",
    brandName: "ADIDAS",
    code: "B37613",
    price: "2.190.000 VND",
    new: "New",
    discount: "20%",
  },
];

export const MLBData = [
  {
    id: 1,
    mainImg: "../images/MLB/Mlb1_1.png",
    extraImgList: [
      "../images/MLB/Mlb1_1.png",
      "../images/MLB/Mlb1_2.png",
      "../images/MLB/Mlb1_3.png",
    ],
    name: "MLB NY PINK",
    brandName: "MLB",
    code: "MLB-NYP",
    price: "2.900.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 2,
    mainImg: "../images/MLB/Mlb2_1.png",
    extraImgList: [
      "../images/MLB/Mlb2_1.png",
      "../images/MLB/Mlb2_2.png",
      "../images/MLB/Mlb2_3.png",
    ],
    name: "MLB NY BLACK WHITE",
    brandName: "MLB",
    code: "MLB-NYBW",
    price: "2.900.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 3,
    mainImg: "../images/MLB/Mlb3_1.png",
    extraImgList: [
      "../images/MLB/Mlb3_1.png",
      "../images/MLB/Mlb3_2.png",
      "../images/MLB/Mlb3_3.png",
    ],
    name: "MLB NY RED WHITE",
    brandName: "MLB",
    code: "MLB-NYRW",
    price: "2.900.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 4,
    mainImg: "../images/MLB/Mlb4_1.png",
    extraImgList: [
      "../images/MLB/Mlb4_1.png",
      "../images/MLB/Mlb4_2.png",
      "../images/MLB/Mlb4_3.png",
    ],
    name: "MLB BOSTON",
    brandName: "MLB",
    code: "MLB-BT",
    price: "2.900.000 VND",
    new: "New",
    discount: "20%",
  },
];

export const PumaData = [
  {
    id: 1,
    mainImg: "../images/PUMA/quan1.jpg",
    extraImgList: [
      "../images/PUMA/quan1.jpg",
      "../images/PUMA/quan1.jpg",
      "../images/PUMA/quan1.jpg",
    ],
    name: "Quần âu nâu sâm",
    brandName: "PUMA",
    code: "362223-02",
    price: "699.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 2,
    mainImg: "../images/PUMA/quan2.jpg",
    extraImgList: [
      "../images/PUMA/quan2.jpg",
      "../images/PUMA/quan2.jpg",
      "../images/PUMA/quan2.jpg",
    ],
    name: "Quần âu xanh đen",
    brandName: "PUMA",
    code: "367516-02",
    price: "799.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 3,
    mainImg: "../images/PUMA/quan3.jpg",
    extraImgList: [
      "../images/PUMA/quan3.jpg",
      "../images/PUMA/quan3.jpg",
      "../images/PUMA/quan3.jpg",
    ],
    name: "Quần âu hàn quốc",
    brandName: "PUMA",
    code: "367516-02",
    price: "399.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 4,
    mainImg: "../images/PUMA/quan4.jpg",
    extraImgList: [
      "../images/PUMA/quan4.jpg",
      "../images/PUMA/quan4.jpg",
      "../images/PUMA/quan4.jpg",
    ],
    name: "Quần âu hàn quốc trắng",
    brandName: "PUMA",
    code: "371511-01",
    price: "499.000 VND",
    new: "New",
    discount: "20%",
  },

  {
    id: 5,
    mainImg: "../images/PUMA/quan3.jpg",
    extraImgList: [
      "../images/PUMA/quan3.jpg",
      "../images/PUMA/quan3.jpg",
      "../images/PUMA/quan3.jpg",
    ],
    name: "Quần âu hàn quốc",
    brandName: "PUMA",
    code: "367516-02",
    price: "399.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 6,
    mainImg: "../images/PUMA/quan4.jpg",
    extraImgList: [
      "../images/PUMA/quan4.jpg",
      "../images/PUMA/quan4.jpg",
      "../images/PUMA/quan4.jpg",
    ],
    name: "Quần âu hàn quốc trắng",
    brandName: "PUMA",
    code: "371511-01",
    price: "499.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 7,
    mainImg: "../images/PUMA/quan2.jpg",
    extraImgList: [
      "../images/PUMA/quan2.jpg",
      "../images/PUMA/quan2.jpg",
      "../images/PUMA/quan2.jpg",
    ],
    name: "Quần âu xanh đen",
    brandName: "PUMA",
    code: "367516-02",
    price: "799.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 8,
    mainImg: "../images/PUMA/quan2.jpg",
    extraImgList: [
      "../images/PUMA/quan2.jpg",
      "../images/PUMA/quan2.jpg",
      "../images/PUMA/quan2.jpg",
    ],
    name: "Quần âu xanh đen",
    brandName: "PUMA",
    code: "367516-02",
    price: "799.000 VND",
    new: "New",
    discount: "20%",
  },
  {
    id: 9,
    mainImg: "../images/PUMA/quan4.jpg",
    extraImgList: [
      "../images/PUMA/quan4.jpg",
      "../images/PUMA/quan4.jpg",
      "../images/PUMA/quan4.jpg",
    ],
    name: "Quần âu hàn quốc trắng",
    brandName: "PUMA",
    code: "371511-01",
    price: "499.000 VND",
    new: "New",
    discount: "20%",
  },
];
